task1_orchestrator:
  ros__parameters:
    frame_id: "map"
    buoy_xy: [10.0, 0.0]
    wall_radius: 2.5
    wall_points: 24
    # GPSのチェックポイント。これを順番に通過していくことを想定している。0番目がstart,最後がゴール位置。
    gps_checkpoint_xy: [[0.0, 0.0], [50.0, 0.0], [50.0, -25.0], [0.0, -25.0]]
    # goalというか収束しきい値というか
    goal_radius: 2.0 

    # check point間の10点、これは大会側から与えられる予定のもの。これを通過していくことを想定している。
    # C2級の曲線で補間していきたい。
    waypoint1_xy: [
      [10.0, 5.0],
      [13.0, 0.0],
      [16.0, -5.0],
      [19.0, -0.5],
      [22.0, 6.0],
      [25.0, 0.0],
      [28.0, -5.0],
      [31.0, -1.0],
      [34.0, 2.0],
      [40.0, 0.0]
    ]

    waypoint2_xy: [
      [24.0, -35.0],
      [15.0, -10.0],
      [8.0, -35.0]
    ]

    seed: 2026
    publish_rate_hz: 2.0
