bms_node:
  ros__parameters:
    transport_mode: "both"   # mros_usb or can or both
    can_rx_id: 1025           # 0x401

    topics:
      # mROS payload: Float32MultiArray with 4 elements [cell1, cell2, cell3, cell4] [V]
      mros_rx: "bms/raw_cells"

      # CAN payload: can_msgs/Frame, 8byte, little-endian uint16[mV] x 4
      can_rx: "bms/can_rx"

      # Normalized output for upper layer
      output: "bms/cell_voltages"
