path_follower_node:
  ros__parameters:
    topic_plan: "/plan"
    topic_odom: "/odom"
    topic_thruster_command: "/thruster_command"

    control_rate_hz: 20.0
    lookahead_distance: 2.0
    goal_tolerance: 1.0

    base_duty: 350
    max_duty: 700
    turn_gain: 450.0
    slowdown_distance: 5.0