<?xml version="1.0"?>
<robot name="njord_asv" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_width" value="1.0" />
  <xacro:property name="base_length" value="1.5" />
  <xacro:property name="base_height" value="0.5" />

  <xacro:property name="lidar_x" value="0.5" />
  <xacro:property name="lidar_y" value="0.0" />
  <xacro:property name="lidar_z" value="0.8" />

  <xacro:property name="imu_x" value="0.0" />
  <xacro:property name="imu_y" value="0.0" />
  <xacro:property name="imu_z" value="0.2" />

  <xacro:property name="gnss1_x" value="-0.5" />
  <xacro:property name="gnss1_y" value="0.4" />
  <xacro:property name="gnss1_z" value="1.0" />

  <xacro:property name="gnss2_x" value="-0.5" />
  <xacro:property name="gnss2_y" value="-0.4" />
  <xacro:property name="gnss2_z" value="1.0" />


  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 0.8"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="livox_frame">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="livox_frame"/>
    <origin xyz="${lidar_x} ${lidar_y} ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
  </joint>

  <link name="gnss_link">
    <visual>
      <geometry>
        <cylinder radius="0.08" length="0.05"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="gnss_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gnss_link"/>
    <origin xyz="${gnss1_x} ${gnss1_y} ${gnss1_z}" rpy="0 0 0"/>
  </joint>

  <link name="gnss_sub_link">
     <visual>
      <geometry>
        <cylinder radius="0.08" length="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="gnss_sub_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gnss_sub_link"/>
    <origin xyz="${gnss2_x} ${gnss2_y} ${gnss2_z}" rpy="0 0 0"/>
  </joint>

</robot>