task2_orchestrator:
  ros__parameters:
    frame_id: "map"
    red_center: [8.0, 2.0]
    green_center: [8.0, -2.0]
    motion_amp: 0.7
    motion_freq_hz: 0.15
    goal_xy: [30.0, 0.0]
    goal_radius: 2.0
    publish_rate_hz: 10.0
    projection_xywh: [15.0, 0.0, 8.0, 5.0]
