<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>task1_sim</name>
  <version>0.1.0</version>
  <description>Task1 simulation orchestrator with cardinal-mark emulation and virtual obstacles.</description>
  <maintainer email="oswystk15662@keio.jp">osw</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>njord_interfaces</depend>
  <depend>buoy_obstacle_publisher</depend>
  <depend>nav2_bringup</depend>
  <depend>natural_cubic_spline</depend>
  <depend>waypoint_publisher</depend>
  <depend>operation_validator</depend>
  <depend>dutyed_tf_pub_with_disturbance</depend>
  <depend>thruster_driver</depend>
  <depend>robot</depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>sensor_sim_with_noise</exec_depend>
  <depend>launch_ros</depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
