#!/usr/bin/env python3
"""Generate the lossless Nav2 base/task/distro overlay set.

The legacy complete parameter files remain the compatibility oracle while the
profile migration is in progress.  This script deliberately performs no
runtime ROS operations; it only factors their YAML mappings deterministically.
"""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
ROBOT_CONFIG = ROOT / "src" / "robot" / "config"
OUTPUT = ROOT / "src" / "mission" / "mission_manager" / "config" / "nav2_profiles"


def _load(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as stream:
        value = yaml.safe_load(stream)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _common(values: list[Any]) -> Any:
    first = values[0]
    if all(value == first for value in values[1:]):
        return first
    if all(isinstance(value, dict) for value in values):
        shared: dict[str, Any] = {}
        for key in values[0]:
            if all(key in value for value in values[1:]):
                item = _common([value[key] for value in values])
                if item is not _MISSING:
                    shared[key] = item
        return shared if shared else _MISSING
    return _MISSING


def _subtract(value: Any, base: Any) -> Any:
    if value == base:
        return _MISSING
    if isinstance(value, dict) and isinstance(base, dict):
        result = {}
        for key, item in value.items():
            remainder = _subtract(item, base.get(key, _MISSING))
            if remainder is not _MISSING:
                result[key] = remainder
        return result if result else _MISSING
    return value


def _merge(base: Any, overlay: Any) -> Any:
    if isinstance(base, dict) and isinstance(overlay, dict):
        result = copy.deepcopy(base)
        for key, value in overlay.items():
            result[key] = _merge(result.get(key, {}), value)
        return result
    return copy.deepcopy(overlay)


def _dump(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by scripts/generate_nav2_profile_overlays.py; do not edit.\n")
        yaml.safe_dump(value, stream, sort_keys=False)


_MISSING = object()


def main() -> None:
    legacy = {
        "task1": "nav2_params_humble.yaml",
        "task2": "nav2_params_task2_humble.yaml",
        "task3": "nav2_params_task3_humble.yaml",
    }
    humble = {name: _load(ROBOT_CONFIG / filename) for name, filename in legacy.items()}
    base = _common(list(humble.values()))
    if not isinstance(base, dict):
        raise ValueError("Nav2 profiles have no common mapping")
    _dump(OUTPUT / "base.yaml", base)

    for profile, full in humble.items():
        task_overlay = _subtract(full, base)
        if not isinstance(task_overlay, dict):
            task_overlay = {}
        _dump(OUTPUT / "tasks" / f"{profile}.yaml", task_overlay)
        assert _merge(base, task_overlay) == full

        jazzy_name = legacy[profile].replace("humble", "jazzy")
        jazzy = _load(ROBOT_CONFIG / jazzy_name)
        jazzy_overlay = _subtract(jazzy, full)
        if not isinstance(jazzy_overlay, dict):
            jazzy_overlay = {}
        _dump(OUTPUT / "distros" / "jazzy" / f"{profile}.yaml", jazzy_overlay)
        assert _merge(full, jazzy_overlay) == jazzy


if __name__ == "__main__":
    main()
