/**:
  ros__parameters:
    # DG-PRO1RWS in TCP client mode -> this node accepts incoming connection
    transport: "tcp_server"

    serial_port: "/dev/ttyUSB0"
    serial_baudrate: 115200

    tcp_host: "10.1.1.4"
    tcp_bind_host: "0.0.0.0"
    tcp_port: 8620

    udp_bind_host: "0.0.0.0"
    udp_port: 5000

    frame_id: "gnss_link"
    fix_topic: "/gnss/fix2"

    read_timeout_ms: 1000
    reconnect_sec: 1.0
