<?xml version="1.0"?>
<package format="3">
  <name>foxglove_image_preview</name>
  <version>0.1.0</version>
  <description>Low-latency cropped JPEG previews for Foxglove.</description>
  <maintainer email="ibo@example.com">ibo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>opencv</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
